//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.31 at 01:26:36 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://appian.com/GoogleGlass/oauth/types")
package com.appian.google.glassware.oauth.types;
