//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.31 at 01:26:36 PM PST
//


package com.appian.googleglass.oauth.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlassAuthType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GlassAuthType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientSecret" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="appianUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accessToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="refreshToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expirationTimeInMillis" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlassAuthType", propOrder = {
    "id",
    "clientId",
    "clientSecret",
    "userId",
    "appianUserId",
    "accessToken",
    "refreshToken",
    "expirationTimeInMillis"
})
public class GlassAuthType {

    protected int id;
    protected String clientId;
    protected String clientSecret;
    protected String userId;
    protected String appianUserId;
    protected String accessToken;
    protected String refreshToken;
    protected Integer expirationTimeInMillis;

    /**
     * Gets the value of the id property.
     *
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the clientId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the clientSecret property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * Sets the value of the clientSecret property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setClientSecret(String value) {
        this.clientSecret = value;
    }

    /**
     * Gets the value of the userId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the appianUserId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAppianUserId() {
        return appianUserId;
    }

    /**
     * Sets the value of the appianUserId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAppianUserId(String value) {
        this.appianUserId = value;
    }

    /**
     * Gets the value of the accessToken property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Sets the value of the accessToken property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccessToken(String value) {
        this.accessToken = value;
    }

    /**
     * Gets the value of the refreshToken property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * Sets the value of the refreshToken property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRefreshToken(String value) {
        this.refreshToken = value;
    }

    /**
     * Gets the value of the expirationTimeInMillis property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getExpirationTimeInMillis() {
        return expirationTimeInMillis;
    }

    /**
     * Sets the value of the expirationTimeInMillis property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setExpirationTimeInMillis(Integer value) {
        this.expirationTimeInMillis = value;
    }

    @Override
    public String toString() {
      return "GlassAuthType [clientId=" + clientId + ", clientSecret=" + clientSecret +
        ", userId=" + userId + ", appianUserId=" + appianUserId + ", accessToken=" + accessToken +
        ", refreshToken=" + refreshToken + ", expirationTimeInMillis=" + expirationTimeInMillis +
        "]";
    }



}
